In [ ]:
#numpy
import numpy as np

# Array creation
a = np.array([1, 2, 3, 4, 5, 6])
print("Original Array:", a)

# zeros()
zeros_array = np.zeros((2, 3))
print("\nZeros Array:\n", zeros_array)

# ones()
ones_array = np.ones((2, 2))
print("\nOnes Array:\n", ones_array)

# arange()
arange_array = np.arange(1, 10, 2)
print("\nArange:", arange_array)

# linspace()
linspace_array = np.linspace(1, 10, 5)
print("\nLinspace:", linspace_array)

# shape
print("\nShape of a:", a.shape)

# reshape()
reshaped = a.reshape(2, 3)
print("\nReshaped Array:\n", reshaped)

# flatten()
flattened = reshaped.flatten()
print("\nFlattened Array:", flattened)

# sum()
print("\nSum:", np.sum(a))

# mean()
print("Mean:", np.mean(a))

# max()
print("Maximum:", np.max(a))

# min()
print("Minimum:", np.min(a))

# sqrt()
print("Square Root:", np.sqrt(a))

# std()
print("Standard Deviation:", np.std(a))

# var()
print("Variance:", np.var(a))

# sort()
unsorted = np.array([4, 2, 1, 6, 3, 5])
print("\nSorted Array:", np.sort(unsorted))

# concatenate()
b = np.array([7, 8, 9])
concatenated = np.concatenate((a, b))
print("\nConcatenated Array:", concatenated)

# split()
split_array = np.split(a, 3)
print("\nSplit Array:", split_array)

# random.rand()
print("\nRandom Float Values:", np.random.rand(3))

# random.randint()
print("Random Integer Values:", np.random.randint(1, 10, 5))

Original Array: [1 2 3 4 5 6]

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]]

Arange: [1 3 5 7 9]

Linspace: [ 1.    3.25  5.5   7.75 10.  ]

Shape of a: (6,)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array: [1 2 3 4 5 6]

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665

Sorted Array: [1 2 3 4 5 6]

Concatenated Array: [1 2 3 4 5 6 7 8 9]

Split Array: [array([1, 2]), array([3, 4]), array([5, 6])]

Random Float Values: [0.36577162 0.16087739 0.35497368]
Random Integer Values: [4 4 3 6 9]


In [ ]:
#1.create a numpy array containing numbers from 1 to 20 using inbuilt function
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#2.create an array of all zeros with 10 elements and convert  it to matrix
arr1=np.zeros(10)
matrix=arr1.reshape(2,5)
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#3.create an array containing even numbers from 2 to 20
arr=np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#4.create an array and find number of dimensions,shape,size,datatype and multiply every element by 2
arr=np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr*2)

1
(5,)
5
int64
[ 2  4  6  8 10]


In [ ]:
#5.create 1D array and find sum,mean ,max and min value
arr5=np.array([4,5,8,6])
print(np.sum(arr5))
print(np.mean(arr5))
print(np.max(arr5))
print(np.min(arr5))

23
5.75
8
4
